# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/utils-qgofer',
                'doc_host': 'https://qgofer.github.io',
                'git_url': 'https://github.com/qgofer/utils-qgofer',
                'lib_path': 'utils_qgofer'},
  'syms': {'utils_qgofer.core': {'utils_qgofer.core.foo': ('core.html#foo', 'utils_qgofer/core.py')}}}
