# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/utils-qgofer',
                'doc_host': 'https://qgofer.github.io',
                'git_url': 'https://github.com/qgofer/utils-qgofer',
                'lib_path': 'utils_qgofer'},
  'syms': { 'utils_qgofer.core': { 'utils_qgofer.core.get_failed_response': ('requests.html#get_failed_response', 'utils_qgofer/core.py'),
                                   'utils_qgofer.core.make_api_request': ('requests.html#make_api_request', 'utils_qgofer/core.py')}}}
